version: '2'
services:
  opencv:
    build:
      context: .
    image: opencv-java
    command: java -Xmx64m -cp target/dependency/*:target/opencv-java-leak-1.0-SNAPSHOT.jar -Djava.library.path=/opencv/opencv-3.3.1/build/lib/ Main